import { useEffect, useRef, useState } from "react";
import Reader, { type SavedBookRef } from "./Reader";
import { PaidResultView } from "./App";
import pdfWorkerUrl from "pdfjs-dist/build/pdf.worker.min.mjs?url";

type Book = {id:string;title:string;source_language?:SavedBookRef["sourceLanguage"];output_language:string;archived:boolean;author:string;subject:string;classification:string};
type Detail = {analyses:Array<{kind:string;language:string;content:Record<string,unknown>}>;audio:Array<{url:string;part:number;voice:string;language:string}>;pdfUrl:string|null;coverUrl:string|null;expiresAt:number};
const sessionKey="spl-supervisor-session-v2";
function rememberedSession(){try{return localStorage.getItem(sessionKey)??"";}catch{return "";}}
async function request<T>(token:string,action:string,bookId?:string,pin?:string):Promise<T> {
 const res=await fetch(import.meta.env.VITE_SUPABASE_URL+"/functions/v1/spl-supervisor-share",{method:"POST",cache:"no-store",credentials:"omit",referrerPolicy:"no-referrer",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,action,bookId,pin})});
 if(!res.ok)throw new Error(res.status===429?"TOO_MANY_ATTEMPTS":res.status===403?"ACCESS_DENIED":"UNAVAILABLE");return res.json();
}
function Cover({pdfUrl,coverUrl,title}:{pdfUrl:string|null;coverUrl:string|null;title:string}) {
 const ref=useRef<HTMLCanvasElement>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{if(coverUrl||!pdfUrl)return;let cancelled=false;let task:ReturnType<typeof import("pdfjs-dist")["getDocument"]>|undefined;
 (async()=>{const pdfjs=await import("pdfjs-dist");if(cancelled)return;pdfjs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl;task=pdfjs.getDocument({url:pdfUrl,disableAutoFetch:true,disableStream:true});const doc=await task.promise;if(cancelled)return;const page=await doc.getPage(1);const viewport=page.getViewport({scale:0.45});const canvas=ref.current;if(!canvas||cancelled)return;canvas.width=viewport.width;canvas.height=viewport.height;const ctx=canvas.getContext("2d");if(ctx)await page.render({canvas,canvasContext:ctx,viewport}).promise;})().catch(()=>{if(!cancelled)setFailed(true);});return()=>{cancelled=true;void task?.destroy();};},[pdfUrl,coverUrl]);
 if(coverUrl)return <img className="shared-cover" src={coverUrl} alt={title}/>;
 if(!pdfUrl||failed)return <div className="shared-cover-placeholder">{title}</div>;
 return <canvas className="shared-cover" ref={ref} role="img" aria-label={title}/>;
}
export default function SharedSupervisor(){
 const [rtl,setRtl]=useState(true),[books,setBooks]=useState<Book[]>([]),[selected,setSelected]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[reading,setReading]=useState(false);
 const [token,setToken]=useState(rememberedSession),[pin,setPin]=useState(""),[checking,setChecking]=useState(false),[authorized,setAuthorized]=useState(false);
 const clearSession=()=>{setAuthorized(false);setToken("");setBooks([]);setSelected("");setDetail(null);setReading(false);try{localStorage.removeItem(sessionKey);}catch{/* optional storage */}};
 const accessFailure=(e:unknown)=>{const code=e instanceof Error?e.message:"UNAVAILABLE";setError(code);setLoading(false);if(code==="ACCESS_DENIED")clearSession();};
 const login=async(e:React.FormEvent)=>{e.preventDefault();if(!/^[0-9]{6}$/.test(pin)||checking)return;setChecking(true);setError("");try{const d=await request<{token:string}>("","login",undefined,pin);setToken(d.token);setPin("");}catch(e){accessFailure(e);}finally{setChecking(false);}};
 const book=books.find(b=>b.id===selected);
 useEffect(()=>{const manifest=document.querySelector<HTMLLinkElement>('link[rel="manifest"]');const previousManifest=manifest?.href;if(manifest)manifest.href=new URL("./supervisor.webmanifest",window.location.href).href;if("serviceWorker" in navigator)void navigator.serviceWorker.register("./sw.js").catch(()=>undefined);const meta=document.createElement("meta");meta.name="referrer";meta.content="no-referrer";document.head.appendChild(meta);try{localStorage.removeItem("spl-supervisor-capability");}catch{/* old access removed */}if(window.location.hash)window.history.replaceState(null,"",window.location.pathname+window.location.search);return()=>{meta.remove();if(manifest&&previousManifest)manifest.href=previousManifest;};},[]);
 useEffect(()=>{if(!token){setLoading(false);return;}let cancelled=false;setLoading(true);request<{books:Book[]}>(token,"list").then(d=>{if(!cancelled){try{localStorage.setItem(sessionKey,token);}catch{/* optional remembering */}setAuthorized(true);setError("");setBooks(d.books);setSelected(d.books.find(b=>b.id==="beef397f-c437-4069-88f6-76868645fb14")?.id??d.books[0]?.id??"");setLoading(false);}}).catch(e=>{if(!cancelled)accessFailure(e);});return()=>{cancelled=true;};},[token]);
 useEffect(()=>{if(!selected||!authorized)return;let cancelled=false;setDetail(null);setLoading(true);setError("");request<Detail>(token,"book",selected).then(d=>{if(!cancelled){setDetail(d);setLoading(false);}}).catch(e=>{if(!cancelled)accessFailure(e);});return()=>{cancelled=true;};},[selected,token,authorized]);
 const analysis=detail?.analyses.find(a=>a.kind==="overview"&&a.language===book?.output_language)??detail?.analyses.find(a=>a.kind==="overview")??detail?.analyses[0];
 const exit=()=>setReading(false);
 const saved:SavedBookRef|null=book?{id:book.id,title:book.title,storagePath:"",sourceLanguage:book.source_language,readOnly:true,sharedAccess:async()=>{const fresh=await request<Detail>(token,"book",book.id);if(!fresh.pdfUrl)throw new Error("ORIGINAL_UNAVAILABLE");return {url:fresh.pdfUrl,expiresAt:fresh.expiresAt};}}:null;
 return <div className="app reviewer-standalone shared-supervisor" dir={rtl?"rtl":"ltr"} lang={rtl?"ar":"en"}><main className="reviewer-standalone-main">
 <p className="prototype-note">{rtl?"للإضافة إلى الشاشة الرئيسية، افتح رابط المستخدم الثابت ثم احفظه.":"To add to your home screen, open the dedicated user link first."} <a href="./user.html">{rtl?"رابط المستخدم الثابت":"Dedicated user link"}</a></p>
 <header className="reviewer-standalone-header"><strong>{rtl?"المكتبة الشخصية الذكية · عرض المستخدم":"Smart Personal Library · User view"}</strong><button className="secondary" onClick={()=>setRtl(!rtl)}>{rtl?"English":"العربية"}</button></header>
 {!authorized?<section className="panel"><h2>{rtl?"دخول المستخدم":"User access"}</h2><p>{rtl?"أدخل الرمز المكون من ستة أرقام الذي أرسله لك صاحب المكتبة.":"Enter the six-digit code shared by the library owner."}</p><form onSubmit={login}><label htmlFor="supervisor-pin">{rtl?"رمز الدخول":"Access code"}</label><input id="supervisor-pin" type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/[٠-٩۰-۹]/g,c=>String(c.charCodeAt(0)-(c<="٩"?1632:1776))).replace(/[^0-9]/g,""))} dir="ltr" style={{display:"block",maxWidth:"18rem",margin:"0.75rem 0",padding:"0.75rem",fontSize:"1.25rem",color:"#111",background:"#fff"}} required/><button type="submit" disabled={checking||loading||pin.length!==6}>{rtl?(checking||loading?"جارٍ التحقق…":"فتح عرض المستخدم"):(checking||loading?"Checking…":"Open user view")}</button></form><p>{rtl?"يتذكر هذا الجهاز الدخول لمدة تصل إلى 30 يومًا، ما لم يتغير الرمز.":"This device remembers access for up to 30 days, unless the code changes."}</p>{error&&<p role="alert">{rtl?(error==="TOO_MANY_ATTEMPTS"?"محاولات كثيرة. انتظر 15 دقيقة ثم أعد المحاولة.":error==="ACCESS_DENIED"?"أدخل رمزًا صحيحًا؛ ربما انتهت صلاحية الدخول السابق.":"تعذر الاتصال. أعد المحاولة."):(error==="TOO_MANY_ATTEMPTS"?"Too many attempts. Wait 15 minutes.":error==="ACCESS_DENIED"?"Enter the correct code; previous access may have expired.":"Connection unavailable. Try again.")}</p>}</section>:reading&&saved?<Reader rtl={rtl} savedBook={saved} onHome={exit} onLibrary={exit} onExitSavedBook={exit}/>:<>
 <section className="reviewer-hero"><span className="eyebrow">{rtl?"عرض خاص للنقاش العلمي":"Private academic review"}</span><h2>{rtl?"مرحبًا بك في المكتبة الشخصية الذكية":"Welcome to the Smart Personal Library"}</h2><p>{rtl?"بدأتُ من كتب اخترتُها وأردتُ قراءتها، لكن الوقت وحجم بعضها ولغتها أخّرت وصولي إليها. صنعتُ هذا النموذج لأستكشف كيف يفتح تنظيم الكتاب وخريطته وخلاصته وصوته مداخل إلى معرفته.":"I started with books I wanted to read, but time, length and language delayed me. I built this prototype to explore how organisation, maps, summaries and audio open paths into their content."}</p><div className="reviewer-research-question"><strong>{rtl?"سؤال للنقاش مع المستخدم":"Working research question"}</strong><p>{rtl?"كيف تؤثر المداخل النصية والصوتية المدعومة بالذكاء الاصطناعي في الوصول إلى معرفة كتاب اختاره المستفيد مسبقًا، وفهمه، والتفاعل مع الأصل حين تسمح اللغة بذلك؟":"How do AI-assisted text and audio entry points affect access to, understanding of and engagement with a self-selected book and, where language permits, its original source?"}</p><small>{rtl?"هذا سؤال أولي؛ فاعلية المداخل وحدودها تحتاج اختبارًا علميًا.":"A working question; effectiveness and limitations require empirical study."}</small></div></section>
 <details className="panel shared-mobile-help"><summary>{rtl?"استخدام العرض على الهاتف":"Use on your phone"}</summary><p>{rtl?"افتح الرابط في Safari على iPhone أو Chrome على Android. لإضافته كتطبيق: اختر «إضافة إلى الشاشة الرئيسية» من قائمة المتصفح. يتذكر هذا الجهاز إذن الدخول عند السماح بالتخزين؛ يلزم الإنترنت لعرض الكتب والمخرجات.":"Open in Safari on iPhone or Chrome on Android. Choose Add to Home Screen from the browser menu. This device remembers access when storage is permitted; books and outputs require an internet connection."}</p></details>{error&&<section className="panel" role="alert">{rtl?(error==="ACCESS_DENIED"?"الرابط غير صالح أو أُلغي. تواصل مع صاحب المكتبة.":"تعذر تحميل المحتوى. حدّث الصفحة وأعد المحاولة."):"The link is invalid or the content is temporarily unavailable."}</section>}
 <label className="shared-book-select">{rtl?"اختر كتابًا":"Choose a book"}<select value={selected} onChange={e=>setSelected(e.target.value)}>{books.map(b=><option value={b.id} key={b.id}>{b.title}{b.archived?(rtl?" · مؤرشف":" · Archived"):""}</option>)}</select></label><div className="reviewer-layout"><aside className="panel reviewer-books"><h3>{rtl?"الكتب المختارة":"Selected books"}</h3><p>{rtl?`${books.length} كتب، منها ${books.filter(b=>b.archived).length} نسخة مؤرشفة`:`${books.length} books; ${books.filter(b=>b.archived).length} archived`}</p>{books.map(b=><button key={b.id} className={b.id===selected?"active":""} onClick={()=>setSelected(b.id)}><strong>{b.title}</strong><small>{rtl?(b.archived?"نسخة معرفية مؤرشفة":"كتاب أصلي نشط"):(b.archived?"Archived knowledge copy":"Active original")}</small></button>)}</aside>
 <section className="reviewer-content">{loading&&<section className="panel" role="status">{rtl?"جارٍ تحميل المخرجات المحفوظة…":"Loading saved outputs…"}</section>}
 {book&&detail&&<><section className="panel reviewer-book-heading"><Cover pdfUrl={detail.pdfUrl} coverUrl={detail.coverUrl} title={book.title}/><div><h3>{book.title}</h3><p>{book.author}</p><p>{book.subject}</p>{book.classification&&<p>{rtl?"التصنيف المقترح: ":"Provisional classification: "}{book.classification}</p>}{detail.pdfUrl?<button className="secondary" onClick={()=>setReading(true)}>{rtl?"افتح الكتاب الأصلي":"Read the original"}</button>:<p>{rtl?"النسخة المؤرشفة تحتفظ بالبطاقة والمخرجات؛ ملف الأصل غير متاح.":"The archived copy retains the card and outputs; its original is unavailable."}</p>}</div></section>
 {analysis&&<section className="panel"><h3>{rtl?"الخلاصة والتحليل المحفوظ":"Saved summary and analysis"}</h3><PaidResultView result={analysis.content} rtl={rtl}/></section>}
 {!!detail.audio.length&&<section className="panel reviewer-audio"><h3>{rtl?"الاستماع إلى الصوت المحفوظ":"Saved audio"}</h3>{detail.audio.map((a,i)=><label className="shared-audio-track" key={i}><span>{rtl?`الجزء ${a.part} · ${a.voice}`:`Part ${a.part} · ${a.voice}`}</span><audio controls preload="none" src={a.url}/></label>)}<button className="secondary" onClick={()=>request<Detail>(token,"book",selected).then(setDetail).catch(()=>setError("UNAVAILABLE"))}>{rtl?"تحديث روابط الاستماع":"Refresh audio links"}</button></section>}
 <section className="panel"><h3>{rtl?"محاور النقاش العلمي":"Academic discussion"}</h3><p>{rtl?"هل المشكلة محددة؟ ما المداخل التي تستحق الاختبار؟ هل يشجع الملخص قراءة الأصل أم الاكتفاء بالمختصر؟ وكيف نقيس الفهم عندما تمنع اللغة قراءة الأصل؟":"Is the problem specific? Which entry points merit testing? Do summaries encourage source reading or replace it? How should understanding be measured when language prevents source reading?"}</p><p>{rtl?"يمكن مناقشة الملاحظات مع صاحب المشروع؛ هذه الصفحة لا تجمع بيانات المشاركين في دراسة.":"Discuss observations with the researcher; this page does not collect participant data."}</p></section></>}
 </section></div></>}
 </main></div>;
}
