import { useEffect, useRef, useState } from "react";
import Reader, { type SavedBookRef } from "./Reader";
import { PaidResultView } from "./App";
import pdfWorkerUrl from "pdfjs-dist/build/pdf.worker.min.mjs?url";

type Book = {id:string;title:string;source_language?:SavedBookRef["sourceLanguage"];output_language:string;archived:boolean;author:string;subject:string;classification:string};
type Detail = {analyses:Array<{kind:string;language:string;content:Record<string,unknown>}>;audio:Array<{url:string;part:number;voice:string;language:string}>;pdfUrl:string|null;coverUrl:string|null;expiresAt:number};
const token = new URLSearchParams(window.location.hash.slice(1)).get("token") ?? "";
async function request<T>(action:string,bookId?:string):Promise<T> {
 const res=await fetch(import.meta.env.VITE_SUPABASE_URL+"/functions/v1/spl-supervisor-share",{method:"POST",cache:"no-store",credentials:"omit",referrerPolicy:"no-referrer",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,action,bookId})});
 if(!res.ok)throw new Error(res.status===403?"ACCESS_DENIED":"UNAVAILABLE");return res.json();
}
function Cover({pdfUrl,coverUrl,title}:{pdfUrl:string|null;coverUrl:string|null;title:string}) {
 const ref=useRef<HTMLCanvasElement>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{if(coverUrl||!pdfUrl)return;let cancelled=false;let task:ReturnType<typeof import("pdfjs-dist")["getDocument"]>|undefined;
 (async()=>{const pdfjs=await import("pdfjs-dist");if(cancelled)return;pdfjs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl;task=pdfjs.getDocument({url:pdfUrl,disableAutoFetch:true,disableStream:true});const doc=await task.promise;if(cancelled)return;const page=await doc.getPage(1);const viewport=page.getViewport({scale:0.45});const canvas=ref.current;if(!canvas||cancelled)return;canvas.width=viewport.width;canvas.height=viewport.height;const ctx=canvas.getContext("2d");if(ctx)await page.render({canvas,canvasContext:ctx,viewport}).promise;})().catch(()=>{if(!cancelled)setFailed(true);});return()=>{cancelled=true;void task?.destroy();};},[pdfUrl,coverUrl]);
 if(coverUrl)return <img className="shared-cover" src={coverUrl} alt={title}/>;
 if(!pdfUrl||failed)return <div className="shared-cover-placeholder">{title}</div>;
 return <canvas className="shared-cover" ref={ref} role="img" aria-label={title}/>;
}
export default function SharedSupervisor(){
 const [rtl,setRtl]=useState(true),[books,setBooks]=useState<Book[]>([]),[selected,setSelected]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[reading,setReading]=useState(false);
 const book=books.find(b=>b.id===selected);
 useEffect(()=>{const meta=document.createElement("meta");meta.name="referrer";meta.content="no-referrer";document.head.appendChild(meta);let cancelled=false;request<{books:Book[]}>("list").then(d=>{if(!cancelled){setBooks(d.books);setSelected(d.books.find(b=>b.id==="beef397f-c437-4069-88f6-76868645fb14")?.id??d.books[0]?.id??"");setLoading(false);}}).catch(()=>{if(!cancelled){setError("ACCESS_DENIED");setLoading(false);}});return()=>{cancelled=true;meta.remove();};},[]);
 useEffect(()=>{if(!selected)return;let cancelled=false;setDetail(null);setLoading(true);setError("");request<Detail>("book",selected).then(d=>{if(!cancelled){setDetail(d);setLoading(false);}}).catch(()=>{if(!cancelled){setError("UNAVAILABLE");setLoading(false);}});return()=>{cancelled=true;};},[selected]);
 const analysis=detail?.analyses.find(a=>a.kind==="overview"&&a.language===book?.output_language)??detail?.analyses.find(a=>a.kind==="overview")??detail?.analyses[0];
 const exit=()=>setReading(false);
 const saved:SavedBookRef|null=book?{id:book.id,title:book.title,storagePath:"",sourceLanguage:book.source_language,readOnly:true,sharedAccess:async()=>{const fresh=await request<Detail>("book",book.id);if(!fresh.pdfUrl)throw new Error("ORIGINAL_UNAVAILABLE");return {url:fresh.pdfUrl,expiresAt:fresh.expiresAt};}}:null;
 return <div className="app reviewer-standalone" dir={rtl?"rtl":"ltr"} lang={rtl?"ar":"en"}><main className="reviewer-standalone-main">
 <header className="reviewer-standalone-header"><strong>{rtl?"المكتبة الشخصية الذكية · عرض المشرف":"Smart Personal Library · Supervisor view"}</strong><button className="secondary" onClick={()=>setRtl(!rtl)}>{rtl?"English":"العربية"}</button></header>
 {reading&&saved?<Reader rtl={rtl} savedBook={saved} onHome={exit} onLibrary={exit} onExitSavedBook={exit}/>:<>
 <section className="reviewer-hero"><span className="eyebrow">{rtl?"عرض خاص للنقاش العلمي":"Private academic review"}</span><h2>{rtl?"مرحبًا بك في المكتبة الشخصية الذكية":"Welcome to the Smart Personal Library"}</h2><p>{rtl?"بدأتُ من كتب اخترتُها وأردتُ قراءتها، لكن الوقت وحجم بعضها ولغتها أخّرت وصولي إليها. صنعتُ هذا النموذج لأستكشف كيف يفتح تنظيم الكتاب وخريطته وخلاصته وصوته مداخل إلى معرفته.":"I started with books I wanted to read, but time, length and language delayed me. I built this prototype to explore how organisation, maps, summaries and audio open paths into their content."}</p><div className="reviewer-research-question"><strong>{rtl?"سؤال للنقاش مع المشرف":"Working research question"}</strong><p>{rtl?"كيف تؤثر المداخل النصية والصوتية المدعومة بالذكاء الاصطناعي في الوصول إلى معرفة كتاب اختاره المستفيد مسبقًا، وفهمه، والتفاعل مع الأصل حين تسمح اللغة بذلك؟":"How do AI-assisted text and audio entry points affect access to, understanding of and engagement with a self-selected book and, where language permits, its original source?"}</p><small>{rtl?"هذا سؤال أولي؛ فاعلية المداخل وحدودها تحتاج اختبارًا علميًا.":"A working question; effectiveness and limitations require empirical study."}</small></div></section>
 {error&&<section className="panel" role="alert">{rtl?(error==="ACCESS_DENIED"?"الرابط غير صالح أو أُلغي. تواصل مع صاحب المكتبة.":"تعذر تحميل المحتوى. حدّث الصفحة وأعد المحاولة."):"The link is invalid or the content is temporarily unavailable."}</section>}
 <div className="reviewer-layout"><aside className="panel reviewer-books"><h3>{rtl?"الكتب المختارة":"Selected books"}</h3><p>{rtl?`${books.length} كتب، منها ${books.filter(b=>b.archived).length} نسخة مؤرشفة`:`${books.length} books; ${books.filter(b=>b.archived).length} archived`}</p>{books.map(b=><button key={b.id} className={b.id===selected?"active":""} onClick={()=>setSelected(b.id)}><strong>{b.title}</strong><small>{rtl?(b.archived?"نسخة معرفية مؤرشفة":"كتاب أصلي نشط"):(b.archived?"Archived knowledge copy":"Active original")}</small></button>)}</aside>
 <section className="reviewer-content">{loading&&<section className="panel" role="status">{rtl?"جارٍ تحميل المخرجات المحفوظة…":"Loading saved outputs…"}</section>}
 {book&&detail&&<><section className="panel reviewer-book-heading"><Cover pdfUrl={detail.pdfUrl} coverUrl={detail.coverUrl} title={book.title}/><div><h3>{book.title}</h3><p>{book.author}</p><p>{book.subject}</p>{book.classification&&<p>{rtl?"التصنيف المقترح: ":"Provisional classification: "}{book.classification}</p>}{detail.pdfUrl?<button className="secondary" onClick={()=>setReading(true)}>{rtl?"افتح الكتاب الأصلي":"Read the original"}</button>:<p>{rtl?"النسخة المؤرشفة تحتفظ بالبطاقة والمخرجات؛ ملف الأصل غير متاح.":"The archived copy retains the card and outputs; its original is unavailable."}</p>}</div></section>
 {analysis&&<section className="panel"><h3>{rtl?"الخلاصة والتحليل المحفوظ":"Saved summary and analysis"}</h3><PaidResultView result={analysis.content} rtl={rtl}/></section>}
 {!!detail.audio.length&&<section className="panel reviewer-audio"><h3>{rtl?"الاستماع إلى الصوت المحفوظ":"Saved audio"}</h3>{detail.audio.map((a,i)=><label className="shared-audio-track" key={i}><span>{rtl?`الجزء ${a.part} · ${a.voice}`:`Part ${a.part} · ${a.voice}`}</span><audio controls preload="none" src={a.url}/></label>)}<button className="secondary" onClick={()=>request<Detail>("book",selected).then(setDetail).catch(()=>setError("UNAVAILABLE"))}>{rtl?"تحديث روابط الاستماع":"Refresh audio links"}</button></section>}
 <section className="panel"><h3>{rtl?"محاور النقاش العلمي":"Academic discussion"}</h3><p>{rtl?"هل المشكلة محددة؟ ما المداخل التي تستحق الاختبار؟ هل يشجع الملخص قراءة الأصل أم الاكتفاء بالمختصر؟ وكيف نقيس الفهم عندما تمنع اللغة قراءة الأصل؟":"Is the problem specific? Which entry points merit testing? Do summaries encourage source reading or replace it? How should understanding be measured when language prevents source reading?"}</p><p>{rtl?"يمكن مناقشة الملاحظات مع صاحب المشروع؛ هذه الصفحة لا تجمع بيانات المشاركين في دراسة.":"Discuss observations with the researcher; this page does not collect participant data."}</p></section></>}
 </section></div></>}
 </main></div>;
}
